# Generated by Django 5.0.4 on 2024-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_album_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(),
        ),
    ]
